{
 "title": "TicketBooking-EventService",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"ticketbooking_services\", service=\"event_service\"}[5m])) by (le, method, route)) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(process_cpu_user_seconds_total{job=\"ticketbooking_services\", service=\"event_service\"}[1m]) +\r\n  rate(process_cpu_system_seconds_total{job=\"ticketbooking_services\", service=\"event_service\"}[1m])\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"ticketbooking_services\", service=\"event_service\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}